import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const studyAbroadData = {
  "United States": {
    overview: "The USA remains the #1 destination for Indian students with over 350,000 enrolled. World-class universities, flexible curriculum, strong research opportunities, and OPT STEM extension (36 months) for STEM graduates. Top courses: CS/AI, Data Science, MBA, Engineering.",
    educationSystem: "4-year bachelor's, 2-year master's, 5-7 year PhD. Liberal arts foundation for UG. Semester system (Aug-Dec, Jan-May). Credit-based flexible curriculum.",
    popularLevels: ["Bachelor's", "Master's", "PhD", "MBA"],
    popularCourses: ["Computer Science", "Data Science", "Artificial Intelligence", "MBA", "Engineering", "Cybersecurity"],
    intakePeriods: ["Fall (August)", "Spring (January)", "Summer (May)"],
    livingCost: 18000,
    currency: "USD",
    language: "English",
    visaInfo: "F-1 Student Visa. STEM OPT allows 36 months work authorization. H-1B visa cap: 85,000/year. Visa interview required.",
    studentVisaProcess: "I-20 from university → SEVIS fee ($350) → DS-160 form → Visa interview → Visa stamping. Processing: 2-4 weeks.",
    workOpportunities: "OPT up to 36 months for STEM. CPT during studies (max 20 hrs/week). Average starting salary: $80,000-$110,000.",
    prOpportunities: "EB-2/EB-3 employment-based green card. Average wait time: 5-10 years for Indian nationals due to per-country caps.",
    costOfLivingRanking: 2,
    educationQualityRanking: 1,
    healthInsurance: "Mandatory. $1,500-$3,000/year through university. Covers basic medical, not dental/vision.",
    culture: "Diverse, individualistic, informal. Strong Indian community in major cities (NY, SF, Chicago, Houston). Campus-centric student life.",
  },
  "United Kingdom": {
    overview: "UK attracts 150,000+ Indian students. 1-year master's degrees save time and money. Graduate Route visa allows 2 years post-study work. Strong in business, law, engineering, and finance.",
    educationSystem: "3-year bachelor's (honours), 1-year master's (taught), 3-year PhD. Focused curriculum without general education requirements. Term system (Oct-Dec, Jan-Mar, Apr-Jun).",
    popularLevels: ["Bachelor's", "Master's", "PhD", "MBA"],
    popularCourses: ["Business Management", "Computer Science", "Law", "Finance", "Engineering", "Data Science"],
    intakePeriods: ["Fall (September)", "Spring (January)", "Summer (May)"],
    livingCost: 16000,
    currency: "GBP",
    language: "English",
    visaInfo: "Student Visa (Tier 4). Graduate Route: 2 years post-study work. No visa interview for most applicants. CAS required from university.",
    studentVisaProcess: "CAS from university → Online application → Biometrics → Visa decision. Processing: 3-6 weeks. Priority service available.",
    workOpportunities: "Graduate Route (2 years). Part-time work: 20 hrs/week during term. Average starting salary: £28,000-£45,000.",
    prOpportunities: "Skilled Worker Visa (5 years → ILR). Graduate Route → Skilled Worker. Health and Care Visa for medical professionals.",
    costOfLivingRanking: 3,
    educationQualityRanking: 2,
    healthInsurance: "Immigration Health Surcharge (£776/year). NHS coverage included. Private insurance optional.",
    culture: "Multicultural, historic, structured. Strong Indian diaspora. Four distinct regions: England, Scotland, Wales, Northern Ireland.",
  },
  Canada: {
    overview: "Canada is the fastest-growing destination for Indian students (300,000+). Most generous post-study work permit (PGWP up to 3 years). Multiple PR pathways. Affordable compared to USA/UK.",
    educationSystem: "4-year bachelor's, 1-2 year master's, 4-5 year PhD. Semester system. Community colleges offer diplomas and certificate programs.",
    popularLevels: ["Bachelor's", "Master's", "Diploma", "PhD"],
    popularCourses: ["Computer Science", "Engineering", "Business", "Data Science", "Healthcare", "Project Management"],
    intakePeriods: ["Fall (September)", "Winter (January)", "Summer (May)"],
    livingCost: 15000,
    currency: "CAD",
    language: "English",
    visaInfo: "SDS (Student Direct Stream) for faster processing. PGWP: up to 3 years after graduation. No visa interview for SDS applicants.",
    studentVisaProcess: "Acceptance letter → SDS account → Upfront medical → Biometrics → Visa decision. SDS processing: 4-6 weeks. Regular: 8-12 weeks.",
    workOpportunities: "PGWP (3 years). Part-time: 24 hrs/week during term. Co-op/internship programs common. Average starting salary: CAD 50,000-75,000.",
    prOpportunities: "Express Entry (CRS score). Provincial Nominee Programs (PNP). Canadian Experience Class. 6 months-2 years for PR after work experience.",
    costOfLivingRanking: 2,
    educationQualityRanking: 3,
    healthInsurance: "Provincial health coverage varies. Some provinces cover international students. Private insurance: $600-$1,000/year.",
    culture: "Welcoming, multicultural, outdoor-oriented. Strong Indian community in Toronto, Vancouver, Brampton, Surrey, Calgary.",
  },
  Australia: {
    overview: "Australia hosts 120,000+ Indian students. World-class universities (Group of Eight). Post-study work: 2-4 years depending on qualification. Strong in engineering, IT, and healthcare.",
    educationSystem: "3-year bachelor's, 1-2 year master's, 3-4 year PhD. Semester system (Feb-Jun, Jul-Nov). Vocational education (TAFE) pathway option.",
    popularLevels: ["Bachelor's", "Master's", "PhD", "Vocational"],
    popularCourses: ["Information Technology", "Engineering", "Nursing", "Business", "Accounting", "Data Science"],
    intakePeriods: ["Semester 1 (February)", "Semester 2 (July)", "Summer (November)"],
    livingCost: 18000,
    currency: "AUD",
    language: "English",
    visaInfo: "Subclass 500 Student Visa. Temporary Graduate Visa (Subclass 485): 2-4 years post-study. Genuine Student requirement. Simplified Student Visa Framework (SSVF).",
    studentVisaProcess: "Confirmation of Enrolment (CoE) → Online application → Health insurance (OSHC) → Biometrics → Visa decision. Processing: 4-8 weeks.",
    workOpportunities: "Subclass 485 (2-4 years). Part-time: 48 hrs/fortnight. Average starting salary: AUD 60,000-85,000.",
    prOpportunities: "Skilled Migration (Points-based). Employer sponsorship. State/territory nominations. Regional visas for extra points.",
    costOfLivingRanking: 2,
    educationQualityRanking: 3,
    healthInsurance: "Overseas Student Health Cover (OSHC) mandatory. $500-$800/year. Covers GP visits, hospital, limited dental.",
    culture: "Relaxed, outdoor, multicultural. Strong Indian community in Sydney, Melbourne, Brisbane, Perth. Beach culture.",
  },
  Germany: {
    overview: "Germany offers tuition-free public university education with €0 semester fees. Over 400,000 international students. Strong in engineering, computer science, and research. Opportunity Card for job seekers.",
    educationSystem: "3-year bachelor's, 2-year master's, 3-5 year PhD. Most public universities charge €0 tuition (semester contribution €150-€400 only). Semester system (Oct-Mar, Apr-Sep).",
    popularLevels: ["Bachelor's", "Master's", "PhD"],
    popularCourses: ["Engineering", "Computer Science", "Data Science", "Mechanical Engineering", "Renewable Energy", "Automotive Engineering"],
    intakePeriods: ["Winter (October)", "Summer (April)"],
    livingCost: 12000,
    currency: "EUR",
    language: "German",
    visaInfo: "Student Visa. Opportunity Card (Job Seeker Visa). 18-month post-study job search visa. Blocked account required (€11,208/year).",
    studentVisaProcess: "University admission → Blocked account (€11,208) → APS certificate → Visa application → Biometrics. Processing: 6-12 weeks.",
    workOpportunities: "18-month job search visa after studies. Part-time: 240 half-days or 120 full-days/year. Average starting salary: €45,000-€58,000.",
    prOpportunities: "EU Blue Card (€41,041/year threshold). Settlement permit after 33 months (21 months with B1 German). Naturalization after 6 years.",
    costOfLivingRanking: 1,
    educationQualityRanking: 1,
    healthInsurance: "Mandatory. Public insurance: €110-€120/month (students under 30). Covers comprehensive medical care.",
    culture: "Efficient, structured. Growing Indian community. Strong industrial base. English-taught programs increasingly available.",
  },
  Ireland: {
    overview: "Ireland is a tech hub (Google, Apple, Meta, Intel HQ). 12,000+ Indian students. Strong CS and business programs. 2-year post-study work visa. English-speaking EU gateway.",
    educationSystem: "3-4 year bachelor's, 1-2 year master's, 3-4 year PhD. Semester system (Sep-Dec, Jan-May). Similar to UK system.",
    popularLevels: ["Bachelor's", "Master's", "PhD"],
    popularCourses: ["Computer Science", "Data Science", "Business Analytics", "Pharmaceuticals", "Engineering", "Finance"],
    intakePeriods: ["Fall (September)", "Spring (January)"],
    livingCost: 14000,
    currency: "EUR",
    language: "English",
    visaInfo: "Student Visa (D-Visa). Stay Back Visa: 2 years after graduation for master's, 1 year for bachelor's. No visa interview for most.",
    studentVisaProcess: "Letter of Acceptance → Online application → Biometrics → Visa decision. Processing: 6-8 weeks.",
    workOpportunities: "Stay Back Visa (2 years). Part-time: 20 hrs/week term, 40 hrs/week holidays. Average starting salary: €35,000-€55,000.",
    prOpportunities: "Critical Skills Employment Permit → Stamp 4 → Citizenship (5 years). Fast track for ICT and healthcare professionals.",
    costOfLivingRanking: 2,
    educationQualityRanking: 3,
    healthInsurance: "Mandatory for non-EEA students. €150-€400/year. University-scheme or private provider.",
    culture: "Friendly, literary, pub culture. Growing Indian community in Dublin, Cork, Galway. English-speaking with Irish (Gaelic) heritage.",
  },
  "New Zealand": {
    overview: "New Zealand offers a safe environment with high-quality education. 8 universities, all in QS top 500. Post-study work visa up to 3 years. Strong agriculture, engineering, and IT programs.",
    educationSystem: "3-year bachelor's, 1-2 year master's, 3-4 year PhD. Semester system (Feb-Jun, Jul-Nov).",
    popularLevels: ["Bachelor's", "Master's", "PhD"],
    popularCourses: ["Information Technology", "Engineering", "Agriculture", "Nursing", "Business", "Hospitality"],
    intakePeriods: ["Semester 1 (February)", "Semester 2 (July)"],
    livingCost: 15000,
    currency: "NZD",
    language: "English",
    visaInfo: "Student Visa. Post-study work visa: 1-3 years depending on qualification level.",
    studentVisaProcess: "Offer of place → Online visa application → Biometrics → Medical certificates → Visa decision. Processing: 4-8 weeks.",
    workOpportunities: "Post-study work visa (1-3 years). Part-time: 20 hrs/week. Average starting salary: NZD 50,000-70,000.",
    prOpportunities: "Skilled Migrant Category (Points-based). Green List occupations for fast-track. Employer-assisted pathway.",
    costOfLivingRanking: 2,
    educationQualityRanking: 3,
    healthInsurance: "Not mandatory but strongly recommended. NZD $300-$700/year for comprehensive cover.",
    culture: "Peaceful, outdoor-oriented, Maori heritage. Small but growing Indian community in Auckland, Wellington, Christchurch.",
  },
};

async function main() {
  for (const [countryName, data] of Object.entries(studyAbroadData)) {
    const country = await prisma.country.findFirst({ where: { name: countryName } });
    if (!country) {
      console.log(`SKIP: ${countryName} not found in DB`);
      continue;
    }

    await prisma.country.update({
      where: { id: country.id },
      data: {
        overview: data.overview,
        educationSystem: data.educationSystem,
        popularLevels: data.popularLevels,
        popularCourses: data.popularCourses,
        intakePeriods: data.intakePeriods,
        livingCost: data.livingCost,
        currency: data.currency,
        language: data.language,
        visaInfo: data.visaInfo,
        studentVisaProcess: data.studentVisaProcess,
        workOpportunities: data.workOpportunities,
        prOpportunities: data.prOpportunities,
        costOfLivingRanking: data.costOfLivingRanking,
        educationQualityRanking: data.educationQualityRanking,
        healthInsurance: data.healthInsurance,
        culture: data.culture,
      },
    });
    console.log(`UPDATED: ${countryName} with study-abroad guidance data`);
  }
  console.log("\nDone! Study abroad country data updated.");
}

main().catch(console.error).finally(() => prisma.$disconnect());
